import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { decodeIndexedPng, encodeIndexedPng, type IndexedImage } from '../lib/png.ts';
import { ROM_DIR, TOOLS_DIR } from '../lib/paths.ts';
import { buildThaiGlyphs, type FontLayout, type ThaiGlyph } from './thai-glyphs.ts';

const CELL_SIZE = 16;
const CELLS_PER_ROW = 16;
const PIXEL_EMPTY = 0;
const PIXEL_FOREGROUND = 1;
const PIXEL_SHADOW = 2;
const PIXEL_BACKGROUND = 3;
const MARK_STEM_COLUMN = 7;

const CHARMAP_PATH = path.join(ROM_DIR, 'charmap.txt');
const FONTS_C_PATH = path.join(ROM_DIR, 'src/fonts.c');
const WIDTHS_JSON_PATH = path.join(TOOLS_DIR, 'font/widths.json');
const PREVIEW_PATH = path.join(TOOLS_DIR, 'font/preview.txt');
const THAI_BLOCK_BEGIN = '@ Thai begin (generated by tools/src/font/build-font.ts)';
const THAI_BLOCK_END = '@ Thai end';
const JAPANESE_SECTION = '@ Hiragana';

export const FONT_LAYOUTS: Record<string, FontLayout> = {
  normal: { sheet: 'latin_normal', widthTable: 'gFontNormalLatinGlyphWidths', bodyTop: 6, bodyRows: 6, lowerMarkTop: 13, height: 15, narrow: false },
  short: { sheet: 'latin_short', widthTable: 'gFontShortLatinGlyphWidths', bodyTop: 6, bodyRows: 6, lowerMarkTop: 12, height: 14, narrow: false },
  narrow: { sheet: 'latin_narrow', widthTable: 'gFontNarrowLatinGlyphWidths', bodyTop: 6, bodyRows: 6, lowerMarkTop: 13, height: 15, narrow: false },
  small: { sheet: 'latin_small', widthTable: 'gFontSmallLatinGlyphWidths', bodyTop: 6, bodyRows: 5, lowerMarkTop: 11, height: 13, narrow: true },
  smallNarrow: { sheet: 'latin_small_narrow', widthTable: 'gFontSmallNarrowLatinGlyphWidths', bodyTop: 6, bodyRows: 5, lowerMarkTop: 11, height: 12, narrow: true },
};

interface Cell {
  width: number;
  pixels: number[][];
}

function renderCell(glyph: ThaiGlyph, layout: FontLayout): Cell {
  const rows = glyph.rows(layout).map((mask, y) => (y < layout.height ? mask : 0));
  const columns = rows.flatMap((mask) => [...Array(8).keys()].filter((x) => mask & (0x80 >> x)));
  if (columns.length === 0) throw new Error(`glyph ${glyph.char} is empty`);

  const minColumn = Math.min(...columns);
  const lastColumn = glyph.isMark ? MARK_STEM_COLUMN + glyph.shiftLeft : Math.max(...columns) + 1;
  const width = lastColumn - minColumn + 1;
  if (width > CELL_SIZE) throw new Error(`glyph ${glyph.char} is wider than a cell`);

  const fill = glyph.isMark ? PIXEL_EMPTY : PIXEL_BACKGROUND;
  const pixels = Array.from({ length: CELL_SIZE }, (_, y) =>
    Array.from({ length: CELL_SIZE }, (_, x) => (x < width && y < layout.height ? fill : PIXEL_EMPTY)),
  );
  const isForeground = (x: number, y: number) => y < CELL_SIZE && x + minColumn < 8 && (rows[y] & (0x80 >> (x + minColumn))) !== 0;

  for (let y = 0; y < CELL_SIZE; y++) {
    for (let x = 0; x < width; x++) {
      if (!isForeground(x, y)) continue;
      pixels[y][x] = PIXEL_FOREGROUND;
      const shadowTargets = glyph.shadowBelow ? [[x + 1, y], [x, y + 1], [x + 1, y + 1]] : [[x + 1, y]];
      for (const [sx, sy] of shadowTargets) {
        if (sx < width && sy < layout.height && !isForeground(sx, sy)) pixels[sy][sx] = PIXEL_SHADOW;
      }
    }
  }
  return { width, pixels };
}

function assertDistinctBases(fontName: string, cells: { glyph: ThaiGlyph; cell: Cell }[]): void {
  const charsByBitmap = new Map<string, string>();
  for (const { glyph, cell } of cells) {
    if (glyph.isMark) continue;
    const bitmap = JSON.stringify(cell.pixels);
    const twin = charsByBitmap.get(bitmap);
    if (twin) throw new Error(`${fontName}: ${twin} and ${glyph.char} render identically; add a body override`);
    charsByBitmap.set(bitmap, glyph.char);
  }
}

function drawCell(image: IndexedImage, slot: number, cell: Cell): void {
  const originX = (slot % CELLS_PER_ROW) * CELL_SIZE;
  const originY = Math.floor(slot / CELLS_PER_ROW) * CELL_SIZE;
  cell.pixels.forEach((row, y) => row.forEach((pixel, x) => (image.pixels[(originY + y) * image.width + originX + x] = pixel)));
}

function readWidthTable(source: string, table: string): { widths: number[]; start: number; end: number } {
  const header = source.indexOf(`${table}[] = {`);
  if (header === -1) throw new Error(`width table ${table} not found`);
  const start = source.indexOf('{', header) + 1;
  const end = source.indexOf('};', start);
  const widths = source.slice(start, end).split(/[\s,]+/).filter(Boolean).map(Number);
  return { widths, start, end };
}

function formatWidthTable(widths: number[]): string {
  const lines: string[] = [];
  for (let i = 0; i < widths.length; i += 16) {
    lines.push('    ' + widths.slice(i, i + 16).map((w) => String(w).padStart(2) + ',').join(' ').replace(/ +$/, ''));
  }
  return '\n' + lines.join('\n') + '\n';
}

function updateCharmap(glyphs: ThaiGlyph[]): void {
  const slots = new Set(glyphs.map((glyph) => glyph.slot));
  const lines = readFileSync(CHARMAP_PATH, 'utf8').split('\n');
  const output: string[] = [];
  let inThaiBlock = false;
  let inLatinSection = true;
  let skipBlankAfterBlock = false;

  for (const line of lines) {
    if (line === THAI_BLOCK_BEGIN) inThaiBlock = true;
    if (inThaiBlock) {
      if (line === THAI_BLOCK_END) {
        inThaiBlock = false;
        skipBlankAfterBlock = true;
      }
      continue;
    }
    if (skipBlankAfterBlock) {
      skipBlankAfterBlock = false;
      if (line === '') continue;
    }
    if (line.startsWith(JAPANESE_SECTION)) {
      inLatinSection = false;
      output.push(THAI_BLOCK_BEGIN);
      for (const glyph of glyphs) output.push(`'${glyph.char}' = ${glyph.slot.toString(16).toUpperCase().padStart(2, '0')}`);
      output.push(THAI_BLOCK_END, '');
    }
    const latinChar = line.match(/^'.+'\s*=\s*([0-9A-F]{2})\s*$/);
    if (inLatinSection && latinChar && slots.has(parseInt(latinChar[1], 16))) continue;
    output.push(line);
  }
  writeFileSync(CHARMAP_PATH, output.join('\n'));
}

function previewCells(title: string, cells: { glyph: ThaiGlyph; cell: Cell }[]): string {
  const symbols = ['.', '#', 's', ' '];
  const blocks: string[] = [title];
  for (let i = 0; i < cells.length; i += 12) {
    const chunk = cells.slice(i, i + 12);
    blocks.push(chunk.map(({ glyph, cell }) => `${glyph.char}${glyph.slot.toString(16)}:${cell.width}`.padEnd(11)).join(' '));
    for (let y = 0; y < CELL_SIZE; y++) {
      blocks.push(chunk.map(({ cell }) => cell.pixels[y].slice(0, 10).map((p) => symbols[p]).join('').padEnd(11)).join(' '));
    }
  }
  return blocks.join('\n');
}

function main(): void {
  const glyphs = buildThaiGlyphs();
  let fontsSource = readFileSync(FONTS_C_PATH, 'utf8');
  const widthsByFont: Record<string, number[]> = {};
  const previews: string[] = [];

  for (const [fontName, layout] of Object.entries(FONT_LAYOUTS)) {
    const sheetPath = path.join(ROM_DIR, 'graphics/fonts', `${layout.sheet}.png`);
    const image = decodeIndexedPng(readFileSync(sheetPath));
    const table = readWidthTable(fontsSource, layout.widthTable);
    const cells = glyphs.map((glyph) => ({ glyph, cell: renderCell(glyph, layout) }));
    assertDistinctBases(fontName, cells);

    for (const { glyph, cell } of cells) {
      drawCell(image, glyph.slot, cell);
      table.widths[glyph.slot] = cell.width;
    }
    writeFileSync(sheetPath, encodeIndexedPng(image));
    fontsSource = fontsSource.slice(0, table.start) + formatWidthTable(table.widths) + fontsSource.slice(table.end);

    const markSlots = new Set(glyphs.filter((glyph) => glyph.isMark).map((glyph) => glyph.slot));
    widthsByFont[fontName] = table.widths.slice(0, 256).map((width, slot) => (markSlots.has(slot) ? 0 : width));
    if (fontName === 'normal' || fontName === 'small') previews.push(previewCells(fontName, cells));
  }

  writeFileSync(FONTS_C_PATH, fontsSource);
  updateCharmap(glyphs);
  writeFileSync(WIDTHS_JSON_PATH, JSON.stringify(widthsByFont) + '\n');
  writeFileSync(PREVIEW_PATH, previews.join('\n\n') + '\n');
  console.log(`Wrote ${glyphs.length} Thai glyphs into ${Object.keys(FONT_LAYOUTS).length} fonts`);
}

main();
